spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/backend}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        default_schema: tabletop-gather
  flyway:
    enabled: true
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/backend}
    user: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    schemas: tabletop-gather
    locations: classpath:db/migration
  docker:
    compose:
      lifecycle-management: start-only
springdoc:
  path: /api-docs
  pathsToMatch: /api/**, /auth/**
