name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nx-lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: npm i --save @nx/nx-linux-x64-gnu @nx/nx-linux-x64-musl # See https://github.com/nrwl/nx/issues/19291
        env:
          spring.security.jwt.secret-key: ${{ secrets.SPRING_SECURITY_JWT_SECRET_KEY }}
          spring.security.jwt.expiration-time: ${{ secrets.SPRING_SECURITY_JWT_EXPIRATION_TIME }}
      - run: npm i --legacy-peer-deps # Nebular is not yet on angular 17- https://github.com/akveo/nebular/issues/3225
      - run: npx nx run-many --verbose -t lint,test,build --parallel=3
