name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nx-lint-build-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: npm i # Can't use ci, because '@nrwl/nx-linux-arm64-gnu' is an optional dependency, and the current package-lock.json is created from a windows host...  https://github.com/nrwl/nx/issues/15452
      - run: npx nx run-many -t lint,test,build --parallel=3
