name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
          cache: 'npm'

      - run: npm ci --force

      - run: npx nx run-many -t lint,test,build --parallel=3
